//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentAccountID { get; set; }
    }
}
