//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int BusinessID { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string CurrencyCode { get; set; }
        public string BusLogoFileName { get; set; }
        public string Address { get; set; }
        public string Slogan { get; set; }
        public string EmailAddress { get; set; }
        public string CellNumber { get; set; }
        public string OfficeNumber { get; set; }
    }
}
