//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_ledger
    {
        public System.DateTime entrydatetime { get; set; }
        public string entrytype { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
        public Nullable<decimal> openingbalance { get; set; }
        public Nullable<decimal> closingbalance { get; set; }
    }
}
