//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class packingtype
    {
        public int PackingTypeID { get; set; }
        public string PackingTypes { get; set; }
    }
}
