//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class posdbEntities : DbContext
    {
        public posdbEntities()
            : base("name=posdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<business> businesses { get; set; }
        public DbSet<businesstype> businesstypes { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<inventory> inventories { get; set; }
        public DbSet<packingtype> packingtypes { get; set; }
        public DbSet<posuser> posusers { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<products_reorderlevel> products_reorderlevel { get; set; }
        public DbSet<purchasesorderdetail> purchasesorderdetails { get; set; }
        public DbSet<purchasesorder> purchasesorders { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<salesorderdetail> salesorderdetails { get; set; }
        public DbSet<salesorder> salesorders { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<tax> taxes { get; set; }
        public DbSet<terminal> terminals { get; set; }
        public DbSet<transaction> transactions { get; set; }
    }
}
