//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Barcode { get; set; }
        public string ImageFileName { get; set; }
        public string GuaranteePeriodYears { get; set; }
        public string WarrantyPeriodYears { get; set; }
        public string ProductSize { get; set; }
        public string ProductWeight { get; set; }
        public string ProductWidth { get; set; }
        public string ProductHeight { get; set; }
        public string ProductColor { get; set; }
        public string ProductCode { get; set; }
    }
}
