//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesorder
    {
        public int OrderID { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<System.TimeSpan> SaleTime { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string ModeOfPayment { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Date_DayofWeek_string { get; set; }
        public Nullable<int> Date_Dayofweek_int { get; set; }
        public Nullable<int> Date_dateofmonth_int { get; set; }
        public Nullable<int> date_month_int { get; set; }
        public string date_month_string { get; set; }
        public Nullable<int> date_year_int { get; set; }
        public Nullable<int> time_hour { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
        public Nullable<int> HoldInvoice { get; set; }
        public string InvoiceID { get; set; }
    }
}
