//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class terminal
    {
        public int TerminalID { get; set; }
        public string TerminalName { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> PrinterType { get; set; }
    }
}
