//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ProductID { get; set; }
        public Nullable<System.DateTime> ProdAddDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PackingTypeID { get; set; }
    
        public virtual PackingType PackingType { get; set; }
        public virtual Product Product { get; set; }
    }
}
