//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<double> PurchaseAmount { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.TimeSpan> PurchaseTime { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TaxesID { get; set; }
        public Nullable<double> CreditAmount { get; set; }
    
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TaxesApplied TaxesApplied { get; set; }
    }
}
