//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int OrderID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<double> SaleAmount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.TimeSpan> SaleTime { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TaxesID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesOrderDetail SalesOrderDetail { get; set; }
        public virtual Store Store { get; set; }
    }
}
