//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public Tax()
        {
            this.TaxesApplieds = new HashSet<TaxesApplied>();
        }
    
        public int TaxesAppliedID { get; set; }
        public string TaxDescription { get; set; }
    
        public virtual ICollection<TaxesApplied> TaxesApplieds { get; set; }
    }
}
