//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxesApplied
    {
        public TaxesApplied()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int TaxesID { get; set; }
        public Nullable<System.DateTime> TaxAppliedDate { get; set; }
        public Nullable<int> TaxAppliedID { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
